version: 0.1.0.{branch}.{build}

clone_depth: 50

environment:
  simplenote_email:
    secure: n025//acdZ0/RDW6A+V2B3+haG+47/AI5jcJXlWYoac=
  simplenote_password:
    secure: BNcALxg5LaOcC3M049bWEgTo4fDd2bVI5vnl3rWlEoQ=

platform: x64

build:
  verbosity: detailed

clone_folder: c:\gopath\src\github.com\sgykfjsm\simplenote

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - make clean
  - make test